services:
  portfolio:
    build: ./website
    env_file:
      - .env
    networks:
      - portfolio

  portfolio-dev:
    build:
      context: ./website
      target: dev
    env_file:
      - .env
    volumes:
      - ./website:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - portfolio

networks:
  portfolio:
    external: true