services:
  production:
    build:
      context: ./website
      target: production
    env_file:
      - ./website/.env
    networks:
      - portfolio

  development:
    build:
      context: ./website
      target: development
    env_file:
      - ./website/.env
    volumes:
      - ./website:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - portfolio

networks:
  portfolio:
    external: true